name: py-loop
channels:
  - defaults
dependencies:
  - matplotlib
  - pip
  - spyder=3.3.4=py37_0
  - pylint=2.3.1=py37_0
  - pip:
    - tensorflow==2.0.0-beta1
    - numpy==1.16.4
    - pandas==0.24.2
    - plotly==4.1.0
    - python==3.7.3
